### ISSUE TITLE
Uncaught ReferenceError: ldf is not defined

### ISSUE THREAD

**Issue by m1ci** [LinkedDataFragments/jQuery-Widget.js#5]
Tried to deploy the client on Apache but I get
```
Uncaught ReferenceError: ldf is not defined at ldf-client-jquery.js:92
```

Tested in Chrome. Any tips why this error occurs?
You can try it here: http://rv2622.1blu.de/ldf-client/jQuery-Widget.js/index.html

**Comment by RubenVerborgh** [comment]
Yes, `http://rv2622.1blu.de/ldf-client/jQuery-Widget.js/deps/ldf-client-browser.js` seems to be empty. Did you generate the file? (Happens automatically with `npm install`.)

**Comment by m1ci** [comment]
I did `npm install`. I also tried `npm install --unsafe-perm` and I get 

```
npm WARN package.json @ No repository field.

> @ postinstall /home/milan/jQuery-Widget.js
> browserify node_modules/ldf-client/browser.js -u stream -o deps/ldf-client-browser.js
./queries-to-json

Error: Cannot find module '/home/milan/jQuery-Widget.js/node_modules/ldf-client/browser.js' from '/home/milan/jQuery-Widget.js'
    at /home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

Should I have browserify installed?

**Comment by RubenVerborgh** [comment]
`npm install` should install browserify for you. Did that go wrong?

**Comment by m1ci** [comment]
I tried once more `npm install` and I get:
```
> @ postinstall /home/milan/jQuery-Widget.js
> browserify node_modules/ldf-client/browser.js -u stream -o deps/ldf-client-browser.js
./queries-to-json

Error: Cannot find module '/home/milan/jQuery-Widget.js/node_modules/ldf-client/browser.js' from '/home/milan/jQuery-Widget.js'
    at /home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/milan/jQuery-Widget.js/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by RubenVerborgh** [comment]
Ah of course, this was changed recently. Will release a new ldf-client version, just a sec.

**Comment by RubenVerborgh** [comment]
[ldf-client v1.3.1](https://github.com/LinkedDataFragments/Client.js/releases/tag/v1.3.1) includes `browser.js`. I've updated this repo to 3c9a7de496564b9096788fcef6571f5095b5274c in order to require 1.3.1.

**Comment by m1ci** [comment]
works! thanks a lot for the super fast update!
